### ISSUE TITLE
making pieces non-static

### ISSUE THREAD

**Issue by quinkennedy** [ofZach/dayForNightSFPC#11]
I was curious about making pieces not static (as requested by the project guidelines). Should we simply be exposing values so they can be controlled (and I assume ultimately animated) by the project organizers? Or should we be including animations in our submissions?

This leads me pretty quickly toward questions about authorship which may become more troublesome with living artists, but it sounds like we have:
1. original artists, whose work was published years/decades ago
2. re-coders who are re-creating artwork, possibly editing it to fit easily with current technology and display media, and adding systems for control/animation
3. curators who are controlling/animating the final result

**Comment by ofZach** [comment]
if you expose parameters that would be ideal -- there's some examples already in the repo of sketches that do so, where there is also corresponding "pseudo" code with those parameters listed so changes get visualized.    It basically involves adding params to a parameter group and editing a pseudo code snippet and using a kind of template style with the name or the param (which will get swapped out for the vale or the param).   Our intent is to record animations using these parameters -- so that you can see a number change in the "psuedo code" and then see the result visually (ala brett victor, etc). 

In terms of authorship it's exactly as you describe -- we're going to be very clear in all the presentation of these works that these are studies, and we will also describe a bit about the process / animation....

If you want to program your animation, I think that's generally also ok -- we were just trying to keep it easy for people, just consider that each sketch will be up for about 15-20 seconds (longer if it's more complex) and the best animations we see are ones that go in a certain direction, from order to chaos, from nothing to something -- either linearly or in more of a sin from 0 to PI (curve from 0 to 1 and back to 0...)

**Comment by quinkennedy** [comment]
Out of curiosity, how are you animating variables? I wonder because I have
an idea for an animation, but don't want to spend hours programming it in
if you have an efficient way for defining and managing animations yourself.

**Comment by ofZach** [comment]
our plan is to use a midi controller (like korg nano) and perform the sketches via slider with a bit of smoothing and then record these paramter changes and replay them so that that sequence can loop....
