### ISSUE TITLE
multiple definition of 'main'

### ISSUE THREAD

**Issue by quinkennedy** [ofZach/dayForNightSFPC#24]
I assume this is only happening in Linux since it has not been fixed yet, but I'm getting a "multiple definition"  errors when I `make`. looks like I'm getting them from `ofxTween/example/map_example_src`

I'm not sure how to remedy these on Linux, should I be able to do it with the command-line project generator? Or editing some project file?

**Comment by roymacdonald** [comment]
Hi, I was the one that put the ofxTween in there, because I'm using it in one of my sketches. I did it because I think that it is simpler to put inside our repo the addons that we are using instead of having everyone complaining and having to download the certain addon because the project doesn't compile anymore after a pull. As so, I think that the addon example can be removed as there's no need to have it, and it will fix your multiple definition of main. I'll do it right now. best!

**Comment by roymacdonald** [comment]
Done!
